# Generated by Django 4.2.9 on 2024-01-04 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creditsearned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('permission', models.FileField(blank=True, null=True, upload_to='permission/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('report', models.FileField(blank=True, null=True, upload_to='report/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('creditsrewarded', models.IntegerField(default=0, editable=False)),
                ('submissiondate', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
