# Generated by Django 4.2.9 on 2024-01-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_creditsearned_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
