# Generated by Django 4.2.9 on 2024-01-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_intern_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='creditsrewarded',
            field=models.IntegerField(default=0),
        ),
    ]
