# Generated by Django 4.2.9 on 2024-01-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_intern_creditsrewarded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intern',
            options={'ordering': ['owner', '-creditsrewarded']},
        ),
    ]
