# Generated by Django 4.2.9 on 2024-01-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_intern_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intern',
            options={'ordering': ['owner']},
        ),
    ]
