# Generated by Django 4.2.9 on 2024-01-18 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_intern_options_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
